//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyInEveryPocket.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public int ContractID { get; set; }
        public long ContractAccountNumber { get; set; }
        public int ContractUser { get; set; }
        public decimal ContractAmount { get; set; }
        public int ContractPeriod { get; set; }
        public System.DateTime ContractExpirationDate { get; set; }
        public double ContractPercent { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual User User { get; set; }
    }
}
