//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyInEveryPocket.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Debit
    {
        public int DebitID { get; set; }
        public string DebitName { get; set; }
        public Nullable<decimal> DebitServiceCost { get; set; }
        public Nullable<decimal> DebitBalancePercent { get; set; }
        public Nullable<decimal> DebitCashback { get; set; }
    }
}
