//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyInEveryPocket.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passport
    {
        public int PassportID { get; set; }
        public int PassportSeries { get; set; }
        public int PassportNumber { get; set; }
        public System.DateTime PassportIssueDate { get; set; }
        public int PassportIssueOrg { get; set; }
    
        public virtual PassportIssueOrganization PassportIssueOrganization { get; set; }
        public virtual User User { get; set; }
    }
}
